# general cfg
image_flip:             True
max_depth:              15
domain:                 rgb

# ros topics
vizTopic:               /viz_path_rgb
imgTopic:               /wide_angle_camera_front/image_raw/compressed
infoTopic:              /wide_angle_camera_front/camera_info
goalTopic:              /mp_waypoint
pathTopic:              /path

# frame ids
robot_frame:            base
odom_frame:             odom

# visualization
viz_path_sem_topic:     /viz_path_rgb
