# planning
main_freq:              5
image_flip:             True
conv_dist:              0.5
max_depth:              15
overlap_ratio_thres:    0.5
depth_zero_ratio_thres: 0.6
# network model
model_save:             models/vip_models/plannernet_env2azQ1b91cZZ_ep100_inputDepSem_costSem_optimSGD
m2f_cfg_file:           models/coco_panoptic/swin/maskformer2_swin_tiny_bs16_50ep.yaml 
m2f_model_path:         models/coco_panoptic/swin/model_final_9fd0ae.pkl
# ros topics
depth_topic:            /depth_camera_front_upper/depth/image_rect_raw
depth_info_topic:       /depth_camera_front_upper/depth/camera_info
rgb_topic:              /wide_angle_camera_front/image_raw/compressed
rgb_info_topic:         /wide_angle_camera_front/camera_info
goal_topic:             /mp_waypoint
path_topic:             /viplanner/path
m2f_timer_topic:        /viplanner/m2f_timer
depth_uint_type:        True
compressed:             True
# frame ids
robot_id:               base
world_id:               odom
# fear reaction
is_fear_act:            False
buffer_size:            3
angular_thred:          0.3
track_dist:             0.5
# smart joystick
joyGoal_scale:          2.5
