# planning
main_freq:              15
image_flip:             True
conv_dist:              0.5
is_sim:                 True
# newwork model
model_save:             /models/plannernet_sim.pt
crop_size:              [360, 640]
uint_type:              True
# images and gaol waypoint topics
depth_topic:            /depth_camera_front_upper/depth/image_rect_raw
rgb_topic:              /wide_angle_camera_front/image_raw/compressed
goal_topic:             /mp_waypoint
path_topic:             /path
image_topic:            /path_image
camera_tilt:            0.3
depth_max:              5.0
# frame ids
robot_id:               base
world_id:               odom
# fear reaction
is_fear_act:            True
buffer_size:            3
angular_thred:          0.3
track_dist:             0.3
# sensor offset
sensor_offset_x:        0.4
sensor_offset_y:        0.0
# smart joystick
joyGoal_scale:          2.5
