# General Configurations
main_freq:            15
image_flip:           True
robot_id:             base
# ROS topics
sem_topic:            /m2f_sem
rgb_topic:            /wide_angle_camera_front/image_raw/compressed
depth_topic:          /depth_camera_front_upper/depth/image_rect_raw
rgb_cam_info_topic:   /wide_angle_camera_front/camera_info
depth_cam_info_topic: /depth_camera_front_upper/depth/camera_info
timer_topic:          /m2f_timer
# Image properties
max_depth:            15
compressed:           True
depth_uint_type:      True
# Mask2FormerInferenceConfig
m2f_config_file:      models/coco_panoptic/swin/maskformer2_swin_tiny_bs16_50ep.yaml 
m2f_model_path:       models/coco_panoptic/swin/model_final_9fd0ae.pkl
