# planning
main_freq:              15
image_flip:             True
conv_dist:              0.5
is_sim:                 False
# newwork model
model_save:             /models/plannernet_real.pt
crop_size:              [360, 640]
uint_type:              True
# images and gaol waypoint topics
depth_topic:            /depth_camera_front_upper/depth/image_rect_raw
goal_topic:             /mp_waypoint
path_topic:             /path
image_topic:            /path_image
# frame ids
robot_id:               base
world_id:               odom
# fear reaction
buffer_size:            10
sensor_view:            1.0