# planning
main_freq:              15
image_flip:             True
conv_dist:              0.5
is_sim:                 True
# newwork model
model_save:             /models/plannernet_sim.pt
crop_size:              [360, 640]
uint_type:              True
# images and gaol waypoint topics
depth_topic:            /depth_camera_front_upper/depth/image_rect_raw
goal_topic:             /mp_waypoint
path_topic:             /path
image_topic:            /path_image
# frame ids
robot_id:               base
world_id:               odom
# fear reaction
is_fear_act:            True
buffer_size:            3
angular_thred:          0.3
track_dist:             0.3