# planning
main_freq:              15
image_flip:             False
conv_dist:              0.5
is_sim:                 True
# newwork model
model_save:             /models/plannernet_vehicle.pt
crop_size:              [360, 640]
uint_type:              False
# images and gaol waypoint topics
depth_topic:            /rgbd_camera/depth/image
goal_topic:             /way_point
path_topic:             /path
image_topic:            /path_image
# frame ids
robot_id:               vehicle
world_id:               map
# fear reaction
buffer_size:            10
sensor_view:            1.0